### ISSUE TITLE
concatenated struct data conversion

### ISSUE THREAD

**Issue by andrescodas** [blink1073/oct2py#107]
Hi

would it be difficult to support the conversion of an array of structs?

example:

function s = structArray()
s = [struct('key','a');struct('key','b');struct('key','c')]
end

For this function oct2py returns only the first struct.

**Comment by blink1073** [comment]
Hi @andrescodas, I am in the middle of a cleanup and streamline that will get us to 4.0.  I verified that your example parses properly with the new version.  Work in progress is in #108.
