### ISSUE TITLE
Handling of keyword arguments is surprising (for Python users)

### ISSUE THREAD

**Issue by shoyer** [blink1073/oct2py#112]
It looks like oct2py parses function calls with keyword arguments using in the [input parser style](http://stackoverflow.com/a/814803/809705), e.g., `f(x=1)` gets converted into `f('x', 1)` when calling Octave. I expected this to somehow do the normal Python thing of passing `1` to the `x` argument (which I guess is not possible in Octave due to a lack of language support).

This seems reasonable, but was pretty surprising to me a novice Matlab/Octave user. It would be nice to clearly document these sort of calling conventions somewhere in the docs.

**Comment by blink1073** [comment]
I'm deprecating the handling of keyword args to function calls altogether in 4.0.  I'll update the docs in 3.x and 4.x to make it clear that the Octave-style argument handling is the one we're using.
