### ISSUE TITLE
Some way to disable Nargout magic

### ISSUE THREAD

**Issue by shoyer** [blink1073/oct2py#113]
I appreciate that this is convenient for working with many Octave/Matlab APIs, but functions returning different numbers of arguments out depending on how many arguments their result is assigned to involves [very fragile magic](https://github.com/blink1073/oct2py/blob/849e2d7aa3cdf15aa52b0e963829de97146acba8/oct2py/utils.py#L15-L46) on the Python side. For example, it works poorly with a notebook/command line interface, because IPython always assigns function results to a single value.

It would be nice if there was a way to disable this behavior and do something more Pythonic (e.g., always return a tuple of all outputs if a function can produce multiple arguments). Maybe it would make sense to add this as an option to the main `Oct2Py` class?

**Comment by blink1073** [comment]
Ha, magic, what magic?  Nothing to see here...

Yep, that sounds like a fair override.
