### ISSUE TITLE
error messages getting cut off

### ISSUE THREAD

**Issue by AetherLorde** [blink1073/oct2py#115]
First off, let me say a great thank you for this project. It is very helpful! 

It looks like the lines beyond the first are being cut off when octave returns an error message. For example, in my code I am getting this: 

error: element number 2 undefined in return list

In the documentation for octave it seems like there are usually lines following the first with more information about the error such as the line number it is called from etc. I could be wrong though, but I wanted to post this here to see if there was anything in oct2py that might be cutting the extra lines off. 

Version: Python 3.5
Oct2Py: 3.9.2

**Comment by blink1073** [comment]
Hi @AetherLorde, this should be fixed by upgrading to version 4.0 `pip install -U oct2py` (I just released it).

**Comment by AetherLorde** [comment]
I am not sure if this actually fixed the issue. I cannot reproduce the issue I was seeing earlier because in my attempts to source my octave file using the octave session produced by oct2py.Oct2Py(), i am getting back 

Oct2PyError: Octave evaluation error:
error: element number 1 undefined in return list

It also seems like some of the simpler functions are now erroring out with a graphics_toolkit failure.

Should I open separate issues for these or are they good in here?

**Comment by blink1073** [comment]
You can post what you're seeing here.

**Comment by AetherLorde** [comment]
I updated the comment above with some more information.

**Comment by blink1073** [comment]
Are you able to post the code you are running?

**Comment by AetherLorde** [comment]
I can post the stuff I am testing with, I just made a little test file to test the sourcing stuff with a couple of globals in it, and I'm attempting to create the oct2py instance and source the file from the ipython repl

test.m
global global_vars;
global testing;

global zero_test = zeros(5)

In IPythonRepl:
oc = oct2py.Oct2Py()
oc.source('test.m')

The repl is running from the same folder as the test.m file.

**Comment by blink1073** [comment]
Thank you, I can reproduce.  It might not be until the weekend until I can work on a fix.

**Comment by AetherLorde** [comment]
No worries! I appreciate you working on this!

**Comment by blink1073** [comment]
@AetherLorde, if you're still seeing any issues, including the graphics_toolkit problem you mentioned, please feel free to open another issue.

**Comment by AetherLorde** [comment]
I don't think this issue is resolved actually. In looking at some more stuff for the other issue, I decided to see if I could confirm it. I have written a very simple .m file with a function that raises an error and then called the function raising the error from the octave command line and from oct2py via the ipython repl. In octave I get the following
```
error: Testing errors in octave
error: called from
    g at line 3 column 3
```
But from oct2py, I still only get the first line
```
Oct2PyError: Octave evaluation error:
error: Testing errors in octave
```

```
1;
function g
  error ("Testing errors in octave")
endfunction
```

**Comment by blink1073** [comment]
Fixed by 7a68142fba65a924809af514a55716d21d86115f, released in 4.0.4 (PyPI done, conda building).

**Comment by AetherLorde** [comment]
Awesome! Thank you!

**Comment by ankostis** [comment]
Could it be occurring again this issue with Octave-5.2.0 _ oct2py 5.0.4?
I'm running an M-file and i'm not getting back any location-context on errors.
