### ISSUE TITLE
Capturing Multiple Returns (again)

### ISSUE THREAD

**Issue by wkew** [blink1073/oct2py#118]
Hi,

I'm trying Oct2Py as a means to bridge my python tools with a large set of octave scripts someone else developed. It is working very well, unfortunately octave functions with variable/multiple outputs are only returning one when I use normal python.

I came across this fixed issue from a couple of years ago - https://github.com/blink1073/oct2py/issues/66 - and using the OctaveMagic approach did seem to solve it, but from the discussion on that page it should have also worked normally? I couldn't find any documentation on this. 

Essentially, 
`[xnew,abnew,widths] = octave.binunif (X, ab, parms, w)`
does not work, returns (either with or without the items in a list)

> ValueError: too many values to unpack (expected 3)

whereas
`%octave [xnew,abnew,widths] = binunif(X, ab, parms, w); -i X,ab,parms,w -o xnew,abnew,widths
`
works perfectly

X is a _n_ x _m_ numpy array (for testing I'm using 50x10000), ab is a 1D array (10000,), parms is a list with a single entry ([1], and w is a float (0.45).
The octave code is attached below.
[mvapack.zip](https://github.com/blink1073/oct2py/files/846160/mvapack.zip)

Apologies if I'm just being silly and missing something obvious? 

(Side note: running it through octavemagic appears to be 5x slower than doing it normally?)

**Comment by blink1073** [comment]
Hi @wkew, we had previously inferred the number of return arguments the same way Octave does, but it relied on an undocumented hack to the Python bytecode, and was confusing to some users.  You can now explicitly pass `nout=3` to your function.

**Comment by wkew** [comment]
Ah, ok - this works now. Thanks!
