### ISSUE TITLE
Cell assignment parsed incorrectly by oct2py

### ISSUE THREAD

**Issue by rrtucci** [blink1073/oct2py#119]
Octavemagic gives me the following erroneous result
https://github.com/rrtucci/bob-sandbox/blob/master/octavemagic-bug.ipynb
If I try the same thing with octave kernel, it works fine
https://github.com/rrtucci/bob-sandbox/blob/master/octave-kernel-okay.ipynb

**Comment by blink1073** [comment]
Hi @rrtucci, as @dsblank suspected, this is a limitation of the magic parsing in `ipython`.  I added a debug print for the line we get from `ipython` in the magic function:

<image src="https://cloud.githubusercontent.com/assets/2096628/24082263/a1150230-0c90-11e7-8959-122fc8ec7c43.png" width=400>

Closing here, as there is nothing we can do in this library, and you have already found a work around.
