### ISSUE TITLE
Errors when running many Oct2Py objects concurrently

### ISSUE THREAD

**Issue by shoyer** [blink1073/oct2py#120]
When I try to run multiple Oct2Py instances concurrently, either with joblib / multi-threading or Apache Beam, I've been getting errors from Oct2Py that only occur when I make a large total number of Octave function calls (more than several hundred).

The errors look like:
```
Oct2PyError: Oct2Py tried to run:
"""
load /tmp/tmpMat3JD/writer.mat "A__" "B__" "C__" "D__" "E__" "F__" "G__" "H__" "I__" "J__" "K__" "L__" "M__"
"""
Octave returned:
error: load: invalid element type = 0
```

with tracebacks of the form:
```
  File ".../oct2py/dynamic.py", line 32, in __call__
    return self._ref()._call(self.name, *inputs, **kwargs)
  File ".../oct2py/core.py", line 460, in _call
    data = self.eval(cmd, temp_dir=temp_dir, **eval_kwargs)
  File ".../oct2py/core.py", line 305, in eval
    out_file=self._reader.out_file)
  File ".../oct2py/core.py", line 626, in evaluate
    raise Oct2PyError(msg)
```

Any idea what's going on here? ~~My best guess is that Python may be running out of temp directories and overwriting old files???~~ This feels like a race condition, but I can't find any non-threadsafe operations (tempfile.mkdtemp *is* allegedly threadsafe).

**Comment by blink1073** [comment]
Which version of `oct2py` is this?

**Comment by shoyer** [comment]
We're still using 3.8.1, though I could try a newer version to see if that helps.

I'll see if I can reproduce this with a toy example.

**Comment by blink1073** [comment]
In general this library wasn't intended to support large parallel loads, do you have the option to use http://wiki.octave.org/Parallel_package?

**Comment by shoyer** [comment]
> In general this library wasn't intended to support large parallel loads, do you have the option to use http://wiki.octave.org/Parallel_package?

Not really, unfortunately. We have some logic in Python that we'd like to parallelize along with Octave, and we want to be able to do true distributed computation across many machines.

It does seem to be an issue with thread-safety. In particular, I can eliminate the issue if I add a global thread lock around scipy's `savemat` routine. Would you be amenable to a pull request adding such a lock to oct2py? I'll also check upstream with SciPy to see if anyone knows what the issue is.

Another simple work around is to use multiple Python processes instead of threads. But sometimes threads are more convenient, for various reasons.

**Comment by blink1073** [comment]
Sure, I'd accept that workaround.  If you make a PR against master I can backport it to 3.x.

**Comment by blink1073** [comment]
I made a `3.x` branch from the `v3.9.2` tag as well if you want to make a PR against that instead.
