### ISSUE TITLE
multiple variable fuction retrevial issue

### ISSUE THREAD

**Issue by hero1900** [blink1073/oct2py#123]
i am calling a m file that is a function that return multiple variables but when assign the result to multiple variables i get an error while if  assigned to single variable it will just return the first returned variable from the function. here is an example:
```
from oct2py import octave
from oct2py import Oct2Py
octave.addpath('/Code/djpg4')
B= octave.rand (3, 2);
filename='/Desktop/123.jpg'
c2=64
im = octave.jpeg_read(filename)
LLRmap,LLpromap,LLRmap_s, q1table, alphat, p0, p1, ppu, pro, dex= getmap(im, 1, c2); % i get error when using this
g=octave.getmap(im, 1, c2) % this suppose to return 10 variables it only return the first one
```

**Comment by blink1073** [comment]
Hi @hero1900, because Python doesn't infer the number of return values the way Octave does, we use the `nout=` parameter in Oct2Py, so the function call should be `octave.getmap(im, 1, c2, nout=10)`.

**Comment by hero1900** [comment]
owh thanks for the information. where i can find good source for how to use oct2py since the main website has just small samples

**Comment by hero1900** [comment]
when i put the number of out put as 10 i still get the error (Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file) but if the nout=5 there will be no error and i can get the first 5 outputs

**Comment by blink1073** [comment]
Hmm, can you give more info about the `getmap` function?  I tried the following:

```octave
function [a, b, c, d, e, f, g, h, i, j] = test_nout()
    a = 1;
    b = 2;
    c = 3;
    d = 4;
    e = 5;
    f = 6;
    g = 7;
    h = 8;
    i = 9;
    j = 10;
end;
```

```python
from oct2py import octave
a = octave.test_nout(nout=10)
a
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
```

**Comment by blink1073** [comment]
Closing for lack of response.
