### ISSUE TITLE
Plotting on Windows does not appear to work

### ISSUE THREAD

**Issue by noteven** [blink1073/oct2py#124]
Good day, it appears that plotting does not work on Windows.  Running the plot demo located here (https://blink1073.github.io/oct2py/source/demo.html) produces a negative float (~-6.x) but no plot window and running the subplot_test provided in ticket #81 produces no perceivable results (no plot, no return). However if one un-comments the saveas() call, the script does output a png file with the appropriate plot.

I should clarify that running the commands within Octave itself works.

EDIT: Tested in an x64 Manjaro virtual machine and the same problem occurs, plot() demo returns ~= -6.x but plot() call from Octave itself runs correctly.

Tested on the following Platforms:
Windows 10 x64
Python 3.6.1 x64 (Clean Miniconda install)
Octave 
graphics toolkit gnuplot (qt crashes Octave)

Windows 7 x32
Python 3.6.1 x32 (Clean Miniconda install)
Octave
graphics toolkit gnuplot and qt

**Comment by noteven** [comment]
Tested the demo and then project I was working on with Oct2Py 3.8.0 and it works perfectly. Maybe problems have to do with the fact that the hard-coded GNUPlot was removed? Either way, rolling back worked fine.

**Comment by blink1073** [comment]
This is now fixed in 4.3.
