### ISSUE TITLE
does oct2py close properly if the octave session is forced to restart?

### ISSUE THREAD

**Issue by rsmith54** [blink1073/oct2py#126]
First wanted to thank you for this package :) 

I'm attempting to use oct2py on a spark cluster, and occasionally my jobs fail with the following error message:

``` 
File "/usr/bin/anaconda/lib/python2.7/site-packages/oct2py/core.py", line 484, in eval
    plot_res=plot_res)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/oct2py/core.py", line 369, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/usr/bin/anaconda/lib/python2.7/site-packages/oct2py/core.py", line 562, in _feval
    raise Oct2PyError('Session died, restarting')
Oct2PyError: Session died, restarting
```

This is happening inside a block:

```
with oct2py.Oct2Py()  as oc:
#do some stuff
```
However, it seems that some stray octave processes are being leftover somehow, and I'm investigating why.   I would appreciate greatly any insight into how this could be happening or how to avoid it.  Thanks!

**Comment by blink1073** [comment]
That error means we got an `EOF` from the process.  It could be that `restart` should be explicitly terminating an existing session if it exists, similar to what `exit` is doing.

**Comment by rsmith54** [comment]
Okay, thanks for the insight.  Do you think the following would be a temporary workaround to ensure that the octave process is closed, as I think this would ensure ```exit()``` is always called?  I'm okay keeping track of failures, I just want to make sure the octave instance is assuredly closed.

```
with oct2py.Oct2Py() as oc:
    try: 
        #do everything with oc in here
    except Oct2PyError as e:
        print("problem with oct2py, exiting")
#close should be called here?
```

**Comment by blink1073** [comment]
I think this will require a change to the core code itself, since it is replacing the old engine without ensuring it is terminated.

**Comment by rsmith54** [comment]
Just fyi, my workaround has at least been working much better than my original code.  I think I only get leftover processes when I kill the python process with ```kill``` or Ctrl+C.

**Comment by blink1073** [comment]
Glad to hear it
