### ISSUE TITLE
Bug in NaN translation

### ISSUE THREAD

**Issue by tyo-lab-nu** [blink1073/oct2py#127]
I have encountered some strange behavior with NaNs when they are used in calculations. I have a very simple .m file that contains the following:

function [res, a, b] = foo(a, b)
res = a * b;
end

When I attempt to run this simple function from Python the output appears as follows:
>>>from oct2py import octave as oc
>>> oc.foo(np.nan, 2, nout=3)
[0, nan, 2]

It seems like the np.nan can get passed in and out of Octave without an issue as one might expect, but as soon as any operation is performed on a NaN inside Octave, the trip back misinterprets the NaN as a 0. 

Any thoughts? Should I expect this behavior?

**Comment by blink1073** [comment]
That is odd.  I updated the function to display the values: 
```
function [res, a, b] = foo(a, b)
res = a * b;
disp(a);
disp(b);
disp(res);
end
```

and I get 

```
In [5]: oc.foo(np.nan, 2, nout=3)
NaN
2
0
Out[5]: [0, nan, 2]
```

But in Octave:

```
octave:3> foo(NaN, 2)
NaN
 2
NaN
ans = NaN
```

I'm not really sure what to do here...

**Comment by tyo-lab-nu** [comment]
I noticed the same thing as you did when running in Octave. It's not immediately clear to me if this is an issue with oct2py itself or if there's something unexpected happening when Octave performs operations on NaNs.

**Comment by blink1073** [comment]
I looked a little closer at this but did not come up with a satisfactory answer.  Something about this [invocation](https://github.com/blink1073/oct2py/blob/d71728b9e30c446131bc2f9a7ccad3a4164d6512/oct2py/_pyeval.m#L57) is causing it to behave differently.

**Comment by kupiqu** [comment]
This example crashes oct2py in my system:
```
Traceback (most recent call last):
  File "pyOct2PyTest2.py", line 4, in <module>
    oc.foo(np.nan, 2, nout=3)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/dynamic.py", line 96, in __call__
    return self._ref().feval(self.name, *inputs, **kwargs)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 379, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 577, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: 'b' undefined near line 2 column 13
```

**Comment by blink1073** [comment]
Thanks for the further info @kupiqu.  This seems to be a bug in the way Octave handles cell array expansion as function arguments, but we rely on this capability to pass the arguments to Octave.

**Comment by kupiqu** [comment]
- Found what is going on:

```
Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
    f   res         1x1                          8  int64

Total is 1 element using 8 bytes

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
    f   a           1x1                          8  double
```

- If one does `oc.foo(np.nan, 2., nout=3)` instead:

```
Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
    f   res         1x1                          8  double

Total is 1 element using 8 bytes

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
    f   a           1x1                          8  double

Total is 1 element using 8 bytes
```

And the result is the expected ([res, a, b]): `[nan, nan, 2.0]`

- I guess Oct2Py would need to ensure all numeric arguments are set to double, which is what Octave/Matlab uses internally to avoid this type of surprises...

- Another surprise because of this is how numbers are rounded to integers ([res, a, b]): `[5, 2.4, 2]`

**Comment by kupiqu** [comment]
Now that we know better the root of the issue, I would suggest to change the title of the issue, as the bug is not related to communicating nan's between python and octave.

Instead the bug results from how each of the languages automatically casts results from operations when variables of different type (e.g., double and int64) are involved.

This will most likely require a change in how numeric values are passed from python to octave (setting all them to double, which is what octave uses internally).

**Comment by kupiqu** [comment]
This is basically what I said above. It's a doc from Matlab, but the same applies to Octave as well:

https://www.mathworks.com/help/matlab/matlab_external/default-numeric-types-in-matlab-and-python.html

**Comment by kupiqu** [comment]
A way to fix this is adding `req.func_args = cellfun(@double,req.func_args,'UniformOutput',0);` in:

```
      try
        req.func_args = cellfun(@double,req.func_args,'UniformOutput',0);
        [result{1:req.nout}] = feval(req.func_name, req.func_args{:});
      catch ME
        if (idx(ME.message, 'nonconformant arguments') != 0)
          args = req.func_args{:};
          [result{1:req.nout}] = feval(req.func_name, args);
        elseif (strcmp(ME.message, 'element number 1 undefined in return list') != 1)
          error(ME);
        else
          result = get_ans(sentinel);
        end

      end
```

Actually, this also fixes the remaining issue I talked about in #135

**Comment by kupiqu** [comment]
I want to note that this is not a proper fix by itself, because one would need to first check that the content is numeric, and only in that case, cast it to double.

**Comment by blink1073** [comment]
Wow, thanks for digging into this, @kupiqu!  We are parsing all of the values before sending them to Octave, so we need to convert integer Python values to float.  We have a property for whether to convert all values (including arrays) to float: https://github.com/blink1073/oct2py/blob/master/oct2py/core.py#L55

**Comment by kupiqu** [comment]
That's nice. I guess it would be good to have it enabled by default to avoid these surprises.

**Comment by kupiqu** [comment]
But it seems it is enabled by default already, isn't it? Is there a bug in there?
