### ISSUE TITLE
Unable to use spline function, even if the input are given properly

### ISSUE THREAD

**Issue by gunjannaik** [blink1073/oct2py#128]
Hi,

I am using spline function in my octave code and calling it from python.

But it throws error of 'x undefined'. Here the x is input of points that I have given. I checked all the variables and there is no issue with them.

But, I am still getting this error.Please help

**Comment by blink1073** [comment]
Hi @gunjannaik, are you able to post the code snippet?

**Comment by blink1073** [comment]
Closing for lack of response.
