### ISSUE TITLE
Not compatible with new version of octave_kernel?

### ISSUE THREAD

**Issue by mickeboj** [blink1073/oct2py#132]
Encountered a problem today when reinstalling oct2py. 
After following the installation guide (did the same steps a couple of days ago and it all worked then) I got error messages when trying to use the library.  Even just using:
 ```python
from oct2py import octave
```
I got some error message ending in something like:
```
No such file or directory: /usr/local/lib/python2.7/dist-packages/octave_kernel/kernel.json
```
After comparing with the previous installation apparently a new version of octave_kernel has come out (0.28.0).

The older installation had octave_kernel==0.27.2 so just using pip to go back to that octave_kernel version for the new installation made oct2py work just fine.

Thanks for a nice library!

**Comment by blink1073** [comment]
Hi @mickeboj, what was the method you used to install `oct2py`?

**Comment by mickeboj** [comment]
Oh, should have specified! 
Used apt-get for octave and python then I used `pip install` `numpy`, `scipy` and then `oct2py`. This resulted in getting the 0.28.0 version of `octave_kernel`

**Comment by blink1073** [comment]
Are you using `sudo`?

**Comment by mickeboj** [comment]
Running as root (both installations have been in a docker container).
`pip` version is `9.0.1`

**Comment by blink1073** [comment]
Ah, I know what the problem is.  Patch release of `octave_kernel` coming soon.  Thanks for the report!

**Comment by blink1073** [comment]
Can you please try `pip install octave_kernel==0.28.1` and see if that fixes it?  (It may not be available right away depending on caching between you and PyPI).

**Comment by mickeboj** [comment]
Seems that it works just fine now! After doing ```pip install numpy scipy oct2py ``` I got `octave_kernel==0.28.1`  which no longer caused any issues when using `oct2py`!

**Comment by blink1073** [comment]
Cheers!
