### ISSUE TITLE
Inability to use package Octave functions since Oct2Py 4.0.0

### ISSUE THREAD

**Issue by scivision** [blink1073/oct2py#135]
Recently I realized that Oct2Py &ge; 4.0 fails when trying to use Octave built-in functions from packages like `signal`. 
For example, `fir1` and `sgolayfilt` fail for me with Oct2Py &ge; 4.0, but work fine with Oct2Py 3.x, in particular Oct2Py 3.9 is what I've reverted to.

Anaconda Python 3.6.4 with Octave 4.2.1 (from Ubuntu 17.10 repo)

Oct2py &ge; 4.0 fails for both `test_*` functions, but works fine for Oct2Py==3.9.0:
https://github.com/scivision/python-matlab-examples/blob/master/test_oct2py.py

The errors are quite bizarre. Things like non-contiguous argument errors, or string type errors, when I'm just trying to use say 
```python
from oct2py import Oct2Py
oc = Oct2Py()
oc.eval('pkg load signal')
x=[0.,0,0,0,0,1,1,1,1,0,0,0,0,0]
y = oc.sgolayfilt(x,3,5) 
```
  
[Gist with input and errors](https://gist.github.com/scivision/86aaeef0d74d4da582625074285f4fe9)

**Comment by blink1073** [comment]
Hi @scivision, I don't have a Linux VM set up at the moment,  what does `type y` give you in Octave when running the equivalent?

**Comment by scivision** [comment]
Thanks. I made a [Gist](https://gist.github.com/scivision/86aaeef0d74d4da582625074285f4fe9) with the inputs and errors.

The funny thing is, if I only give the first argument, the Oct2Py call works. I deliberately made an example where I used defaults for 2nd and 3rd input variables to `sgolayfilt`.

This odd behavior is not limited to `sgolayfilt`, it was just a convenient example.

And again, if I use `oct2py` &le; 3.9 everything works as expected, but breaks for `oct2py` &ge; 4.0.0

I tried `image` functions like `imshear()` and `entropy()`, and they worked from oct2py 4.0.6.  So it could be a `signal` specific thing?

**Comment by blink1073** [comment]
Okay, it looks like the parameters are getting mangled on their way to Octave.  I should have my other computer set up including a Linux VM by this weekend to do some more digging.

**Comment by blink1073** [comment]
Turns out I need to send the laptop in for repairs, good times

**Comment by scivision** [comment]
https://travis-ci.org/scivision/python-matlab-examples/builds/329238269

This result from Octave 14.04 with Octave 3.8.1 and Python 3.6.3.  So it's not apparently related to a particular octave version

**Comment by kupiqu** [comment]
This example works fine in my system once I use the changes from commit 52206dc5e07dc3e69cc99015926bb03a8703fe44

**Comment by kupiqu** [comment]
Unfortunately the latest changes (at least in conda version) creates a crash in how the arguments are passed (it was working before):

```
Traceback (most recent call last):
  File "pyOct2PyTest2.py", line 5, in <module>
    y = oc.sgolayfilt(x,3,5) 
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/dynamic.py", line 96, in __call__
    return self._ref().feval(self.name, *inputs, **kwargs)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 379, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 579, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: =: nonconformant arguments (op1 is 1x5, op2 is 3x5)
```

**Comment by kupiqu** [comment]
If I use master I get this instead:
```
Traceback (most recent call last):
  File "pyOct2PyTest2.py", line 5, in <module>
    y = oc.sgolayfilt(x,3,5) 
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/dynamic.py", line 96, in __call__
    return self._ref().feval(self.name, *inputs, **kwargs)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 379, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 579, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: index(120,_): but index has size 1x0 (note: variable 'index' shadows function)
```

**Comment by kupiqu** [comment]
Although this won't fix the crash, I would suggest renaming index to idx or alike to avoid shadowing Octave's index function.

**Comment by scivision** [comment]
Thanks, I noticed this was closed and it works now. We patiently waited for and really appreciate the renewed stream of Oct2Py development!

**Comment by blink1073** [comment]
Thanks for your patience and for the encouragement!
