### ISSUE TITLE
The result of pushing a numpy array makes me some confused

### ISSUE THREAD

**Issue by Hzzone** [blink1073/oct2py#137]
Here is my code:
```
from oct2py import octave
import cv2
import numpy as np
# octave.eval("pkg load image")
img = cv2.imread('/Users/HZzone/Desktop/lena.jpg').astype(np.float64)
octave.push('img', img)
octave.eval("imwrite(img, '1.jpg')")
```
when I wanna push a numpy array from an image which looks like:
![lena](https://user-images.githubusercontent.com/19267349/35587998-563d10d2-063a-11e8-8425-c5c8f325c9b7.jpg)
 
but the image saved became nonsense:
![1](https://user-images.githubusercontent.com/19267349/35588065-7fd76fe6-063a-11e8-91de-275ea70cbcf1.jpg)

**Comment by Hzzone** [comment]
python 2.7.14, macos sierra!

**Comment by blink1073** [comment]
Hi @Hzzone, my guess is that image needs to be scaled in intensity to display properly.

**Comment by blink1073** [comment]
You could output a portion of the matrix to make sure it isn't getting lost in translation.

**Comment by Hzzone** [comment]
@blink1073 Thanks for you help. I think it's a wrong use of python and matlab, since the channel sequence of images read by Python `cv2.imread()` is BGR but matlab is RGB... For me I have read image once again to solve this problem, maybe it also can be solved by transposing the numpy array.

**Comment by blink1073** [comment]
Closing since there is nothing to change in oct2py.  I don't want to modify the user's data any more than strictly necessary.  Cheers!
