### ISSUE TITLE
ImportError: No module named oct2py

### ISSUE THREAD

**Issue by ahillie2** [blink1073/oct2py#138]
Hi,

I've been trying to run a simple set up using oct2py, but i can't seem to even import the library.  I believe I have followed the set up instructions precisely. Do you have any idea what might be generating this error?

![img_0707](https://user-images.githubusercontent.com/36988063/36895411-663b576c-1dd4-11e8-867b-ee43a618c6e3.jpeg)

**Comment by blink1073** [comment]
Hi @ahillie2, did you run `sudo pip install oct2py`?

**Comment by ahillie2** [comment]
Thanks for the fast reply.  I tried sudo pip install oct2py(all of the guides say pip install oct2py) and it changed the error I was receiving. It was throwing a similar error with regards to Scipy now. I assume I will have to install this as well?  I will investigate it further this afternoon.

**Comment by ahillie2** [comment]
@blink1073, When I try to run the code now, I get the same error but with regards to scipy.  I tried running **sudo apt-get scipy** and **pip install scipy** and **sudo pip install scipy**.

The error from my code is :
![img_0713](https://user-images.githubusercontent.com/36988063/36915864-cd9959f2-1e17-11e8-9ddf-96c69a839747.jpg)

The error from running sudo pip install scipy is:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i5QO7i/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-P1Bw8I-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i5QO7i/scipy/

Do you have any suggestions? Thanks for any help!

**Comment by blink1073** [comment]
Is `sudo which pip` different from `which pip`?  If so, I would recommend:

- ```rm `which pip``
- `sudo pip uninstall scipy`
- `sudo pip uninstall oct2py`
- `pip install oct2py --user`

Which should install `oct2py` and `scipy` in `~/.local`, but still be available from `sudo python`.
You may also need to upgrade your `pip`: `sudo pip install -U pip`.

**Comment by ahillie2** [comment]
Everything was all cleared up, I followed a youtube video to download scipy.  Everything is working correctly now.

Thanks so much for your help!
