### ISSUE TITLE
I can not find the octave.exe after installing octave

### ISSUE THREAD

**Issue by WilesDai** [blink1073/oct2py#141]
When installing oct2py library on Python, I was required to have GNU Octave installed in my path, in another word, setx PATH "%PATH%; where the folder has the file “octave.exe”.

However, I can not find the octave.exe after installing octave using the installation packages released in https://www.gnu.org/software/octave/#install and I have tried all the three installation packages for Windows-64.

Hence, how can I solve this problem?

**Comment by WilesDai** [comment]
> You don't have a C:/Octave/Octave-x.y.z/bin?

I have, so set "C:/Octave/Octave-x.y.z/bin" as the System Path？ I have tried but the oct2py failed to work. Please  give me some advice. Many thanks!

**Comment by WilesDai** [comment]
> If you open a Windows Command Prompt, and type `octave-cli`, does octave run?

After typing  `octave-cli`, the information of octave like the "version" and "Copyright"  is presented in the Windows Command Prompt. But the octave software itself doesn't run.

**Comment by WilesDai** [comment]
> If you open a Windows Command Prompt, and type `octave-cli`, does octave run?

After typing octave-cli, the information of octave like the "version" and "Copyright" is presented in the Windows Command Prompt.

**Comment by blink1073** [comment]
It looks like it is on your PATH then.  Does this print anything (assumes python 3)?

`python -c "import shutil;print(shutil.which('octave-cli'))"`

**Comment by WilesDai** [comment]
> It looks like it is on your PATH then. Does this print anything (assumes python 3)?
> 
> `python -c "import shutil;print(shutil.which('octave-cli'))"`
Many thanks for your replying! After this step, "C:\Octave\octave-4.4.1-w64\bin\octave-cli.EXE" is printed.

**Comment by WilesDai** [comment]
> It looks like it is on your PATH then. Does this print anything (assumes python 3)?
> 
> `python -c "import shutil;print(shutil.which('octave-cli'))"`

After this step, "C:\Octave\octave-4.4.1-w64\bin\octave-cli.EXE" is printed. I still can not figure out the problem.

**Comment by WilesDai** [comment]
> It looks like it is on your PATH then. Does this print anything (assumes python 3)?
> 
> `python -c "import shutil;print(shutil.which('octave-cli'))"`
Dear Sir, I  tried a lower version of Octave which has a octave.exe after installing and it worked. Many thanks for your help!

**Comment by blink1073** [comment]
Glad it is working now!
