### ISSUE TITLE
Returning empty string result failes

### ISSUE THREAD

**Issue by xorxx** [blink1073/oct2py#142]
I have an empty string result in the return values of my octave function and get the following error when executing it:
```
warning: save: wrong type argument '<unknown type>'
oct2py.utils.Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file
```

**Comment by blink1073** [comment]
Hi @xorxx, which version of oct2py and scipy were you using?

**Comment by xorxx** [comment]
I used oct2py version 4.0.6

**Comment by blink1073** [comment]
Hmm, I am unable to replicate.  Do you have some sample code I can try?

![image](https://user-images.githubusercontent.com/2096628/56890914-69fab500-6a40-11e9-9790-61f66154e764.png)

**Comment by xorxx** [comment]
Sorry, I have a rather large program creating a lot of result values. Maybe the cause of my error is not the empty string (which is there too) but some other object/type returned.
My string value is placed in an octave structure, perhaps this is a hint?
In your function foo you could try:
```
x.a=1
x.b='abc'
x.c=''
```

**Comment by blink1073** [comment]
No, that works fine:

![image](https://user-images.githubusercontent.com/2096628/56891670-daa2d100-6a42-11e9-8cc3-2042bc6c98bf.png)

**Comment by xorxx** [comment]
Sorrym I have no further suggestions on how to reproduce the error message.
Thank you for your efforts!

**Comment by blink1073** [comment]
Cheers, closing as answered for now.
