### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'enabled.'

### ISSUE THREAD

**Issue by andrescodas** [blink1073/oct2py#154]
I'm getting **random** errors like this:
```
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 183, in pull
    exist = self._exist(name)
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 677, in _exist
    exist = int(resp.split()[-1])
ValueError: invalid literal for int() with base 10: 'enabled.'
```
I say it is random because I'm unable to reproduce it when I'm debugging, and therefore I'm unable to find its root cause.

**Comment by blink1073** [comment]
Wow, that is an interesting one.  The `exist()` function is supposed to return an integer.  Do you have some code that at least randomly triggers the bug?

**Comment by andrescodas** [comment]
Unfortunately, I'm unable to share this project with you. I have been trying to isolate it into a minimum failing example without success.  I will share an example later if I isolate it.  Other unexpected error I'm experiencing is:

```
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 379, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/usr/local/lib/python2.7/dist-packages/oct2py/core.py", line 561, in _feval
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/octave_kernel/kernel.py", line 241, in eval
    raise e
TypeError: _log() got an unexpected keyword argument 'end'
```
where **_log()** is a function in the logging package

Not sure if it is related

**Comment by blink1073** [comment]
Ah, I know where that error is coming from.  I'm not sure when I'm going to have the bandwidth to work through these issues.

**Comment by andrescodas** [comment]
Is there a workaround I can use in the meantime?

**Comment by blink1073** [comment]
For now you can go to `/usr/local/lib/python2.7/dist-packages/metakernel/replwrap.py` and comment out this section:

```python
                    try:
                        self.child.expect([u('\r')], timeout=0)
                        stream_handler('\r', end='')
                        if got_cr:
                            stream_handler(self.child.before, end='')
                        got_cr = True
                    except pexpect.TIMEOUT:
                        break
```

**Comment by blink1073** [comment]
The problem is that we're passing `log.info` as the `stream_handler`, which doesn't support an `end` keyword arg.  I'm not yet sure how to properly handle this.

**Comment by blink1073** [comment]
Thinking out loud: given that we're tied to using logging for the logger, I don't think we can support true streaming output (like a progress bar), so I think the octave engine needs a parameter for this that it passes to replwrap to determine whether to use the code path above.

**Comment by blink1073** [comment]
Alternatively, there are two types of receivers: line and stream.  We would use a line receiver from oct2py, but the Octave kernel would be able to support a stream.

**Comment by blink1073** [comment]
cf https://github.com/Calysto/metakernel/pull/188 for an impending fix.

**Comment by andrescodas** [comment]
Thanks for the fix!.  I couldn't reproduce the errors after updating.
