### ISSUE TITLE
 Octave evaluation error: error: cannot read beyond the last record

### ISSUE THREAD

**Issue by marcoistasy** [blink1073/oct2py#160]
Hello,

I am running `oct2py` with `fieldtrip` to try to read some eeg data. However, when I set all my path variables

```
octave.addpath('/home/Desktop/fieldtrip-master/fileio')
octave.addpath('/home/Desktop/fieldtrip-master/fileio/private')
octave.addpath('/home/Desktop/fieldtrip-master')
octave.addpath('/home/Desktop/fieldtrip-master/utilities')
```

and try to read in the file using this function `file = octave.read_neuralynx_ncs('/home/Desktop/data/LACC1_0001.ncs')` I recieve the following error message:

```
Oct2PyError: Octave evaluation error:
error: cannot read beyond the last record
```

I am wondering why this might be the case?

**Comment by blink1073** [comment]
Hi @marcoistasy, does that code work when run from Octave itself?

**Comment by blink1073** [comment]
Closing for lack of response.
