### ISSUE TITLE
Incorrect parsing of multiple "cell" data type

### ISSUE THREAD

**Issue by shlomotz** [blink1073/oct2py#167]
0

I have the following ovtav function : (XY_Stimuli.m)

function [Xhex,Ynhex]=XY_Stimuli(x_amplitude,n_amplitude,b0,b1)
X=x_amplitude*(rand(1024,1)-0.5);
n=n_amplitude*(rand(1024,1)-0.5);
Y=filter([b0,b1],1,X);
Yn=Y+n;
X=floor(X*2^15+0.5)/2^15;
Yn=floor(Yn*2^15+0.5)/2^15;
for sample=1:1024
 if(X(sample)>0)
    X(sample)=X(sample)*2^15;
else
    X(sample)=X(sample)*2^15+2^16;
end
if(Yn(sample)>0)
     Yn(sample)=Yn(sample)*2^15;
else
    Yn(sample)=Yn(sample)*2^15+2^16;
end   

Xhex{sample}=dec2hex(X(sample));    
Ynhex{sample}=dec2hex(Yn(sample));     
end

But when the function is called from python

>>> x, y = octave.XY_Stimuli(1,0.2,0.5,0.3)
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
 ValueError: not enough values to unpack (expected 2, got 1)

The same with : >>> [x, y] = octave.XY_Stimuli(1,0.2,0.5,0.3)

( As a workaround I merged the 2 output into one output , and then split it in the python code)

**Comment by blink1073** [comment]
Hi @shlomotz, does it work if you  use `x, y = octave.XY_Stimuli(1,0.2,0.5,0.3, nout=2)` to specify 2 outputs expected?

**Comment by shlomotz** [comment]
Hi blink1073,

Thanks a lot , 'nout=2' does solved the issue.
Could you please elaborate or give a references about "nout" ? (why/when it's required)

Best Regards,
Shlomo

**Comment by blink1073** [comment]
There's an example in the [demo docs](https://github.com/blink1073/oct2py/blob/82d2ae7d8f641b2759b83a62db3528efe1e54382/docs/source/demo.rst) and the [API docs](https://github.com/blink1073/oct2py/blob/82d2ae7d8f641b2759b83a62db3528efe1e54382/oct2py/core.py#L407).
If you'd like to make a PR adding it to the README I would be happy to accept.

**Comment by yasirroni** [comment]
Added to README in [7f46a30](https://github.com/blink1073/oct2py/pull/170/commits/7f46a3025568937dd04ab7cafaa99c603be2e121)

**Comment by yasirroni** [comment]
> There's an example in the [demo docs](https://github.com/blink1073/oct2py/blob/82d2ae7d8f641b2759b83a62db3528efe1e54382/docs/source/demo.rst) and the [API docs](https://github.com/blink1073/oct2py/blob/82d2ae7d8f641b2759b83a62db3528efe1e54382/oct2py/core.py#L407).
> If you'd like to make a PR adding it to the README I would be happy to accept.

You should mark this issue as closed after the merge of [a10b64a](https://github.com/blink1073/oct2py/commit/a10b64ad83c6de5e28106cdfccc353a5712b3107) and release 5.2.

**Comment by yasirroni** [comment]
Solved in [f16f0bd](https://github.com/blink1073/oct2py/pull/170/commits/f16f0bd36c650a4f813790b2c48f3436031daf1a)
