### ISSUE TITLE
oct2py & pyinstaller

### ISSUE THREAD

**Issue by gonebanana** [blink1073/oct2py#173]
Good afternoon!
Consider such situation.
I have a simple Octave (5.1.0.0 version) function, that should display a message by 
`disp('WELCOME TO OCTAVE')`
and save 2x3 array to the file by 
`dlmwrite(strcat(path,'/test.csv'), a, ',')`
I use this through PyCharm by
`oct = oct2py.Oct2Py(temp_dir=resource_path("."))`
`oct.test_writing(os.path.abspath("."))`
and it makes output `WELCOME TO OCTAVE` and creates a file test.csv. 

**But** when I m making an executable .exe through pyinstaller and run, it just skips this actions and nothing happens! there is an error:  `error: '_pyeval' undefined near line 1 column 1` ,   but execution finishes correctly. 

**But** if I save an array to the python workspace and after that save it to file by
`res = oct.test_writing(os.path.abspath("."))`
`np.savetxt('output_data.csv', res, delimiter=',')`
 .exe doesn`t show a message but .csv file appears.

So, I need to have an opportunity to save some data during octave code while running an .exe. I'm using oct2py via conda. 
If it is a question for you, can you please help me? Can't find anything about it in the net.

Very thank you!
(this is my first question on github, so i'm sorry if something's wrong)

**Comment by blink1073** [comment]
Hi @gonebanana, I'm not familiar with pyinstaller, I'm not sure how to help debug this.  It sounds like it might not have picked up the [`_pyeval`](https://github.com/blink1073/oct2py/blob/8970a6692ced5d8d0c3b85b9c8c769416fbf86d9/oct2py/_pyeval.m) file.

**Comment by gonebanana** [comment]
Yes, it sounds like this :D 
There is one thing more. 
I made there a comment [https://github.com/blink1073/oct2py/issues/144#issuecomment-686291429](url) about adding file reader.mat
I just add an existing file reader.mat (made by the same code out of exe), but it is not still creating by itself inside.
May be you can know if it can cause some problems?

**Comment by blink1073** [comment]
The [`reader.mat`](https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L537) is created as needed.  I'm not sure if pyinstaller is doing something that is preventing that from happening.

**Comment by gonebanana** [comment]
Hello again!
The file writer.mat as I understand, is creating here:
https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L554
and file reader.mat in its turn should be created in octave func _pyeval.m througt the code
https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L563
So, if i have an error  `error: '_pyeval' undefined near line 1 column 1`, i'm not getting into this function, so the file reader.mat is not created by itself. 
But the quastion is that, why he daesn't see (looks like variable name) '_pyeval'?.... It's not like he can't find a func because in this case there should be an error FileNotFound (or something like this).

**Comment by blink1073** [comment]
In this line we try and add `_pyeval.m` to the list of scripts: https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L524.  You could try using `oct.test_writing(os.path.abspath("."), verbose=True)` to see if it gives more insight.   I'm going to be away from my computer for the next couple days.

**Comment by gonebanana** [comment]
> I'm going to be away from my computer for the next couple days.

I was also too)))
The line of code you sent is the part of function `restart`, however, inside `try` at line  563, there is no such action.... I even made a ` step into` debug during process and it didn't go through https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L524 after 
https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L563
May be, I understand something wrong.... Anyway, ` verbose=True` didn`t give any axtra results :(

**Comment by gonebanana** [comment]
Please, look one more time!
I'm using environmental variables with the aim of using exe at any computer (even without Octave), so i hide a folder with `octave-cli.exe` and file `kernel.json` inside exe:
`os.environ["OCTAVE_EXECUTABLE"] = resource_path('Octave-5.1.0.0\\mingw64\\bin\\octave-cli.exe')`
`os.environ["OCTAVE_KERNEL_JSON"] = resource_path('Octave-5.1.0.0\\kernel.json')`
`import oct2py`
`oct = oct2py.Oct2Py(temp_dir=resource_path("."))`
I'm trying another way now, that uses oct2py methods `push` and `get_pointer`. For example:
`oct.push(['phase'], 1)`
` phase = oct.get_pointer('phase').value`
This works perfectly via PyCharm while the exe from console gives such errors:
![image](https://user-images.githubusercontent.com/44446694/92483679-c4d61c00-f1f1-11ea-84da-37d667ae9501.png)
with `oct.eval('phase = 1;')` the same.
It looks like there is the problem with placement of variables! (
May be you have any idea?
Thank you!

**Comment by blink1073** [comment]
I'm sorry, I'm really not sure what is happening.  I don't use Windows.  `restart()` is called in the [constructor](https://github.com/blink1073/oct2py/blob/a10b64ad83c6de5e28106cdfccc353a5712b3107/oct2py/core.py#L76).

**Comment by gonebanana** [comment]
okay((
thank you
on this way, i'm closing the issue
