### ISSUE TITLE
How can I load an octave package from python?

### ISSUE THREAD

**Issue by Antonio-Nappi** [blink1073/oct2py#175]
I need to execute some matlab code, so I installed this library. In the matlab I call the "fmincon" function, and in the python script there is an error because it says that "fmincon" is undefined. I think that it's because the package it's not loaded, so could I load dynamically a package?

**Comment by blink1073** [comment]
Hi @Antonio-Nappi, it looks like you need the `optim` package installed locally:

https://octave.org/doc/v4.2.1/Using-Packages.html
https://octave.sourceforge.io/optim/function/fmincon.html

**Comment by Antonio-Nappi** [comment]
Yes, I have it installed, I solved my problem just loading the package before the script.
