### ISSUE TITLE
qt library 

### ISSUE THREAD

**Issue by arnodelorme** [blink1073/oct2py#183]
QT is the default Octave library and the most compatible with Matlab. 

I was able to trick oct2py to use it by forcing it to call "octave" (GUI) instead of "octave-cli" (simply changed the symbolic link of octave-cli on OSx). On Windows, I was not so successful.
However, is there a better way to do that? I was reading that it might be possible to set some parameters for the back end of oct2py #129

Also, the issue with using QT with oct2py is that figures created by Octave cannot be closed - except using the command "octave.close()" However, if users try to close the figure, the octave-cli program crashes and it is not possible to do anything anymore. 

Using oct2py default version (pip) for Python 3.8.5. Using Octave 6.1 on OSx Mojave.

**Comment by blink1073** [comment]
Hi @arnodelorme, plotting is best-effort for this library and I only have bandwidth to support `gnuplot`.
