### ISSUE TITLE
Specifying temp_dir in %%octave magic cell

### ISSUE THREAD

**Issue by adityaapte** [blink1073/oct2py#191]
Is it possible to specify temp_dir in %%octave octavemaic cell similar to oct2py. https://blink1073.github.io/oct2py/source/api.html

**Comment by blink1073** [comment]
Hi @adityaapte, not currently, would you like to submit a PR to add the [option](https://github.com/blink1073/oct2py/blob/f81139ba1fbc9473efaebebe6b3a6a80c863f913/oct2py/ipython/octavemagic.py#L164)?

**Comment by adityaapte** [comment]
Thanks @blink1073 . Just created the PR. I am not sure when the temp_dir gets deleted.
https://github.com/blink1073/oct2py/pull/192

**Comment by blink1073** [comment]
Fixed by #192
