### ISSUE TITLE
%%octave magic cells not working in oct2py 5.4.2

### ISSUE THREAD

**Issue by locastre** [blink1073/oct2py#214]
Hi, we've installed the newest oct2py v.5.4.2 in a Google Colab notebook running Python v3.7.12. We load the  extension to use cell magics via `%load_ext oct2py.ipython`. When we try to run `%%octave` magic cells, the processes in the cell will run successfully, but after completion it will throw an error referring to a random tmp directory (not the one which oct2py is using):

```
%%octave

disp('hi')
//
hi
Exception ignored in: <finalize object at 0x7f88dd4fd980; dead>
Traceback (most recent call last):
  File "/usr/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib/python3.7/tempfile.py", line 936, in _cleanup
    _rmtree(name)
  File "/usr/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpr8lx7rqj'
```
This error does not occur if we run `octave.disp('hi')` in a Python cell. The same error occurs if we specify the temp location via `%%octave --temp_dir` at the top of the magic cell.

We have replicated the error with oct2py v5.4.2 running Jupyter on a local Windows machine.

**Comment by locastre** [comment]
Could this bug be from the `octave_kernel` update rather than `oct2py`?

**Comment by blink1073** [comment]
No, this is an issue with `oct2py`, but I just tried on OSX and it works fine for me.  I don't currently have access to a Windows machine.

**Comment by locastre** [comment]
Thank you very much for your reply. We will test it out on our local Mac machine.

Do you have access to test oct2py in the Linux on https://colab.research.google.com/? We experienced the problem in that environment too. If it is of help, here is the notebook we use, for reference. 

https://github.com/cerr/octave-colab/blob/master/octave_deploy.ipynb

**Comment by yasirroni** [comment]
```
%load_ext oct2py.ipython
```

```
%%octave
disp('hi')
```

```
import oct2py
oct2py.__version__
# '5.2.0'
```

```
import octave_kernel
octave_kernel.__version__
# '0.32.0'
```

I can't replicate the error on windows 10

**Comment by yasirroni** [comment]
@locastre How about using `oct2py` class?

**Comment by blink1073** [comment]
Should be addressed by https://github.com/blink1073/oct2py/pull/216
