### ISSUE TITLE
How do I use imported Octave functions in oct2py?

### ISSUE THREAD

**Issue by jcollignon** [blink1073/oct2py#218]
Hi,
Recently I started using Octave to run Matlab scripts on Google Colab's iPython notebook.  Turns out I need to use functions within Octave's "image" package which doesn't come with the main installation of Octave.  Does oct2py have a way of installing and loading missing Octave packages that would normally need to be downloaded from the Octave sourceforge?
Thank you!

**Comment by blink1073** [comment]
Hi @jcollignon, assuming the Octave is set up properly to install packages, you should be able to run:

```
%%octave
pkg install -forge image
```

If you get an error about C++, then Octave itself isn't set up for compilation on Colab.

**Comment by jcollignon** [comment]
I tried using the above, but Colab throws this error:
`UsageError: Cell magic %%octave not found.`
Earlier I was able to use simpler Matlab scripts that I know have functions only within the main distribution of Octave, but the work I'm doing needs to go slightly beyond that.  An example Matlab script `octave_test.m` I'm trying to call is below:
```
x = 3;
y = 2;
display(x+y)
my_image = imread('/content/gdrive/My Drive/path_to_image.jpg');
[circle_centers, circle_radii] = imfindcircles(my_image, [10 40], 'Sensitivity', 0.95);
display(circle_radii(1))
```
Trying to run this script throws this error:
```
Oct2PyError: Octave evaluation error:
error: 'imfindcircles' undefined near line 5 column 32
error: called from:
    octave_test at line 5, column 30
    _pyeval at line 57, column 28
    run at line 86, column 5
```
I am able to call the `display` and `imread` functions without issues, but `imfindcircles` is not a function in the main distribution of Octave.  At first I tried opening Octave using `!octave` which creates a subshell within the output of the python script where I can install the image package.  The problem I was having was trying to load the image package: I can only use `pkg load image` from within the Octave subshell, not within the Python script itself, currently making it impossible to use this package outside of the subshell.

**Comment by blink1073** [comment]
In order run the octave magic, you have to run `%load_ext oct2py.ipython` in a cell first.  Then you can run the cell contents I gave above.   If you're using an `Oct2Py` object, you can call `.eval("pkg install -forge image")` on it to install the package.

**Comment by jcollignon** [comment]
It's been a while since I last posted, but I want to say thanks for your help in resolving this problem.  I was able to successfully get the package loaded up on Colab after running the above, and have the tar.gz files for the package downloaded from the sourceforge in case I need to install them.

**Comment by blink1073** [comment]
Great, thanks for the follow up!

**Comment by blink1073** [comment]
Something went wrong on the [import](https://github.com/blink1073/oct2py/blob/75e3f032dfe00ab554826e7025cb35357bdfbce2/oct2py/__init__.py#L48).  Please try `import oct2py` in a cell and see what gets printed, and open a new issue with the traceback.

**Comment by fangq** [comment]
thanks @blink1073. I wasn't sure what happened, but running the same commands again on a new runtime worked fine and both `%octave` and `%%octave` magic commands worked nicely.

one quick question: do you by any chance know if there is a way to tell octave to print abbreviated array in Jupyter notebook when ';' is omitted? I had a few occasions that octave prints large arrays to the notebook and it took too long to complete. I had to restart the runtime.

I found a [few commands](https://stackoverflow.com/a/13515224/4271392) to control the verbosity of printing structs, but not for arrays.

**Comment by blink1073** [comment]
No, but you can use `verbose=False` in the function call.
