### ISSUE TITLE
push will push Cell 

### ISSUE THREAD

**Issue by yasirroni** [blink1073/oct2py#223]
While trying to solve https://github.com/blink1073/oct2py/pull/222, I've found out that a simple push will push newly created Cell object. Why? And where is it called?

Recreate bug:

```python
class Cell(np.ndarray):
    def __new__(cls, value, session=None):
        """Create a cell array from a value and optional Octave session."""
        # Use atleast_2d to preserve equality between Octave size() and Python numpy.shape()
        value = np.atleast_2d(np.asarray(value, dtype=object))

        if not session:
            return value.view(cls)

        # Extract the values.
        obj = np.empty(value.size, dtype=object).view(cls)
        for (i, item) in enumerate(value.ravel()):
            obj[i] = _extract(item, session)
        obj = obj.reshape(value.shape)
        print('obj', obj)
        return obj
```

```python
m.push('x', 3)

# obj [['__no_value__']]
# obj [[Cell([['__no_value__']])]]
```

**Comment by yasirroni** [comment]
Further inspections, pull also go through Cell __new__ method but didn't create a Cell object.

**Comment by blink1073** [comment]
The `__no_value__` cell is a sentinel value created in [`_pyeval.m`](https://github.com/blink1073/oct2py/blob/e8ebd99c4fa3d667e871f3f01ee9f6652a29949f/oct2py/_pyeval.m#L20).  We use it is a stand-in for [`None`](https://github.com/blink1073/oct2py/blob/09d3ee077bd62c2d0d279b311a8f74bedf97429d/oct2py/core.py#L595).
