### ISSUE TITLE
[Question] Properly end session

### ISSUE THREAD

**Issue by yasirroni** [blink1073/oct2py#227]
With the following code:

```python
m1 = Oct2Py()
m1.push('x', 1)

m1 = Oct2Py()
m1.pull('x', 1) # error
```

We can see that each call of `Oct2Py()` calls a new session. This is good.

But, if we didn't properly end the session, what happen to the memory and process of octave? With above example, 

```python
m1 = Oct2Py()
m1.push('x', 1)

m1 = Oct2Py() # what happen to old Octave session? Is it properly shut down?
```

**Comment by blink1073** [comment]
Good point, we should probably add a `Oct2Py.__del__` method that calls `Oct2Py.exit`

**Comment by yasirroni** [comment]
If I simply restart the python kernel (ipython) or close the python on terminal (using exit()), I'm all good right?

This is a simple question.

____

> Good point, we should probably add a Oct2Py.__del__ method that calls Oct2Py.exit

Working on this FOSS project make me learn lots of Python, haha. But I might skip for this fix job for now.

**Comment by yasirroni** [comment]
> Working on this FOSS project make me learn lots of Python, haha. But I might skip for this fix job for now.

Hmm, after some reading, is it this easy? https://github.com/blink1073/oct2py/pull/230

**Comment by blink1073** [comment]
> If I simply restart the python kernel (ipython) or close the python on terminal (using exit()), I'm all good right?

No, I think we were actually leaking octave processes because we didn't have an explicit cleanup.  Thanks for the fix!
