### ISSUE TITLE
_exist function not removing special characters from response

### ISSUE THREAD

**Issue by snheffer** [blink1073/oct2py#308]
Hi,

from what I can tell, 

```
def _exist(self, name):
        """
       Test whether a name exists and return the name code.

        Raises an error when the name does not exist.
        """
        if not self._engine:
            msg = "Session is not open"
            raise Oct2PyError(msg)
        resp = self._engine.eval(cmd, silent=True).strip()
        exist = int(resp.split()[-1])
```

isn't removing some character sequences from the response integer.
e.g. I get "invalid literal for int() with base 10: '\r\n\x1b[?2004h'", when exist should equal 5 with msg equalling "ans = 5", meaning a builtin ("addpath")

which suggests \r\n\x1b[?2004h isnt getting stripped from the string, as I don't think it's getting split properly.
I'm running oct2py on 3.9.

**Comment by blink1073** [comment]
Hi @snheffer, this is a known issue, with a workaround in pexpect: https://github.com/pexpect/pexpect/issues/669#issuecomment-758109973

**Comment by snheffer** [comment]
Thanks for getting back to me so quickly @blink1073 , yes that fixed my issue, it's a interesting quirk I hadn't encountered before with bash!
