### ISSUE TITLE
Oct2py hangs in Windows

### ISSUE THREAD

**Issue by spinningplates** [blink1073/oct2py#63]
Oct2py hangs in Windows after importing "octave" in either Python or IPython in Windows command line.  Currently using Windows 7, Python 2.7.8, Anaconda 2.1.0, oct2py 2.4.0.  It also hangs during the nosetests after cloning the repo.

**Comment by spinningplates** [comment]
I've just confirmed that the 2.4.2 release works.  Thanks!

**Comment by blink1073** [comment]
Great!  You're very welcome!

**Comment by uozden** [comment]
Dear Blink1075
Which version of oct2py does work with Octave 4.0.0 on Windows ?
Thanks in advance
