### ISSUE TITLE
Too aggressively deleting tmpfiles

### ISSUE THREAD

**Issue by nils-werner** [blink1073/oct2py#67]
I am currently trying to run several oct2py-utilising processes in parallel and they start interfering because they delete each other's MAT files. I noticed that you're running a very aggressive cleanup method:

    def _remove_temp_files(dirname):
        """
        Remove the created mat files in the user's temp folder
        """
        import os
        import glob

        for fname in glob.glob(os.path.join(dirname, 'tmp*.mat')):
            try:
                os.remove(fname)
            except OSError:  # pragma: no cover
                pass

Now without having dug deeper into the code to see what exactly is needed, may I suggest using a context manager like the following to create tempfiles?

    class tempfile:
        """ Context for temporary file.
        Will find a free temporary filename upon entering
        and will try to delete the file on leaving

        """
        def __init__(self, suffix=''):
            self.suffix = suffix

        def __enter__(self):
            import tempfile as tmp
            self.handle, self.name = tmp.mkstemp(suffix=self.suffix)
            return self.name

        def __exit__(self, type, value, traceback):
            try:
                os.close(self.handle)
                os.remove(self.name)
            except OSError as e:
                if e.errno == 2:
                    pass
                else:
                    raise e

you would use it like

    with tempfile(suffix=".mat") as matfile:
        oct2py.whatever(matfile)

and the context manager would clean up the file afterwards itself (even in the case of exceptions)

**Comment by blink1073** [comment]
Thanks for pointing that out.  It will require a bit of restructuring, but your solution sounds good.

**Comment by blink1073** [comment]
@nils-werner, it should be fixed now in the latest master if you'd like to try it out.  I plan to make another release this weekend.

**Comment by blink1073** [comment]
Closing as fixed.
