### ISSUE TITLE
datatype of empty string returned is <u1

### ISSUE THREAD

**Issue by neotheicebird** [blink1073/oct2py#69]
function x = return_empty_str()
    x=''

this function when called by Oct2py returns:
    
    array([], dtype='<U1')

while

    function x = return_empty_str()
    x='foo'

when called gives
    
    u'foo'

Why don't we get `u''` in the first case?

*Oct2py version 3.1.0, python version 2.7*

**Comment by blink1073** [comment]
Good point, thanks, fixed!

**Comment by neotheicebird** [comment]
awesome!
