### ISSUE TITLE
OSX maverick issue

### ISSUE THREAD

**Issue by mabelcalim** [blink1073/oct2py#70]
Hi,
I'm using the oct2py in OSX Maverick, and I don't know how to fix this issue:

import oct2py

ImportError: dlopen(/Users/usuario/src/scipy/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Users/usuario/src/scipy/scipy/special/_ufuncs.so
  Reason: image not found

I downloaded octave: brew install octave
GNU Octave, version 3.8.2

and pip installed oct2py

Thanks in advance
Mabel

**Comment by moorepants** [comment]
NumPy and SciPy are dependencies of oct2py. Do you have them installed?

**Comment by blink1073** [comment]
@mabelcalim, specifically, do you see the same error with `python -c "import scipy"` from the command line?

**Comment by mabelcalim** [comment]
Hi,

you guys were right. The scipy was installed via pip and the brew, then there
was conflict.
I just uninstall scipy and install it again and everything just work fine
now.
Thanks!
Cheers
Mabel

On 26 May 2015 at 08:37, Steven Silvester <notifications@github.com> wrote:

> @mabelcalim <https://github.com/mabelcalim>, specifically, do you see the
> same error with python -c "import scipy" from the command line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blink1073/oct2py/issues/70#issuecomment-105328777>.
>



-- 
------------------------------------------------------------------------

*Mabel Calim Costa*CSIRO / Australia
+61 0431593444

Instituto Nacional de Pesquisas Espaciais - INPE
Cachoeira Paulista -SP
+55 (12) 3186 - 8552 (ramal *8575*)
-------------------------------------------------------------------------

**Comment by blink1073** [comment]
Great, happy coding!
