### ISSUE TITLE
calling octave asynchronously 

### ISSUE THREAD

**Issue by markuman** [blink1073/oct2py#72]
from oct2py import Oct2Py
    oct1 = Oct2Py()
    oct2 = Oct2Py()
    ret = oct1.eval('pause(10)')

This will block the process for 10 seconds. Is there any way to call it asynchronously and check later `ret.done()` if `oct1` is done? This is how the official matlab python engine works.

**Comment by blink1073** [comment]
You'll have to use threading or separate processes to achieve what you want.  See `https://github.com/blink1073/oct2py/blob/master/oct2py/thread_check.py` for an example.
