### ISSUE TITLE
oct2py hangs when called via nosetests or py.tests on python 2.7

### ISSUE THREAD

**Issue by ocefpaf** [blink1073/oct2py#73]
Hi,

I have a weird testing framework to compare the results of a python library with a MatlabTM library.  The tests runs just fine on Python 3, but hangs on Python 2.   Here is a gist of the code:

```python
rootpath = os.path.dirname(__file__)
octave = Oct2Py(timeout=3)  # Hangs here
path = os.path.join(rootpath, 'matlab_library')
_ = octave.addpath(octave.genpath(path))
```

Note that everything works fine for Python2 when called outside `nose` or `pytest`.

Here is the full travis log:

https://travis-ci.org/pyoceans/python-seawater/builds/69282280

**Comment by blink1073** [comment]
Hi @ocefpaf, nothing jumps out at me as you while your build would fail, unless `__file__` is not what you think it is.  Perhaps print the value of `path` so it shows up in the error report?  You might also try breaking the first command into two parts, I'm not sure I've tested a nested call as the first call (though I'll go ahead and do that in light of this question).

```python
path = os.path.join(rootpath, 'seawater_v3_3')
print(path)
genpath = octave.genpath(path)
print(genpath)
_ = octave.addpath(genpath)
```

**Comment by ocefpaf** [comment]
Thanks for the quick response!

> Hi @ocefpaf, nothing jumps out at me as you while your build would fail,
unless __file__ is not what you think it is. Perhaps print the value of
path so it shows up in the error report?

Printing displays the directory as expected.

You might also try breaking the first command into two parts, I'm not sure
I've tested a nested call as the first call (though I'll go ahead and do
that in light of this question).

I will try that as soon as I can. But everything works as is on Python 3,
and even Python 2 if I do not call via py.test or nose.

> path = os.path.join(rootpath, 'seawater_v3_3')
> print(path)
> genpath = octave.genpath(path)
> print(genpath)
> _ = octave.addpath(genpath)

**Comment by blink1073** [comment]
I meant that `__file__` could be different when using a test runner.

**Comment by ocefpaf** [comment]
> I meant that __file__ could be different when using a test runner.

I ~~debugged~~ printed it while using the test runner.  If I omit the line `genpath = octave.genpath(path)` it prints the right thing.  If I run the code "as is" it hangs and nothing gets printed, not even the calls before that line!  My knowledge of test runner is very limited to understand what happens under the hood.

This might not be oct2py's fault...  So I am closing this until I find some time to investigate more.  What puzzles me is that everything works just fine in Python3 :unamused:

**Comment by blink1073** [comment]
I ran a similar check where the first call was nested, and it passed on Python 2.7, so I am at a loss, unless the combination of the two commands was taking longer than 3 seconds in your build...

**Comment by ocefpaf** [comment]
Nope, it hangs forever.  The 3 seconds I introduced to avoid waiting.

**Comment by blink1073** [comment]
Darn.
