### ISSUE TITLE
oct2py imports octave but hangs when calling an octave function.

### ISSUE THREAD

**Issue by KainoaCulverhouse** [blink1073/oct2py#74]
Hi,

I am using Linux CentOS6.6 Operating System and use Python 2.6 when trying to communicate with octave. I use Python2.6 because when I installed oct2py ('pip install oct2py') the package installed in the same path as Python2.6. As for octave, I am running octave 4.0.0 which is also in the same path as python2.6 (both in '/usr/bin') (I believe that means they are in the same path, I am not sure).

I can open python2.6 in terminal and type in 'from oct2py import octave'... When doing this python2.6 continues and moves to the next line displaying '>>>' though the octave gui will open in a separate window (I am unsure if this should be the case)... The next step I take is simply try to do an octave command such as ('>>> octave.ones(3)') and what happens next is python2.6 goes to the next line not displaying '>>>' and seams to hang (nothing happens next).. I have to exit terminal or use 'ctrl+z' to stop and exit python2.6

Do you have any suggestions as to why this is happening? I cannot seem to figure out why I can't carry out octave commands.

Thank you for the help.

**Comment by blink1073** [comment]
Hi @KainoaCulverhouse, unfortunately the default behavior for the new Octave has changed (loading a GUI), and I have not yet figured out a backwards-compatible way of handling it.  In the meantime, you can point to the new `octave-cli` program using `from oct2py import Oct2Py; octave = Oct2Py(executable=<path_to_octave_cli_executable>)`.

**Comment by KainoaCulverhouse** [comment]
Hello @blink1073, thank you for the reply I appreciate it. I followed your instructions and resulted in the following error:

>>> from oct2py import Oct2Py
>>> octave = Oct2Py(executable='/usr/bin/octave-cli-4.0.0')
>>> octave.ones(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/oct2py/core.py", line 592, in __getattr__
    doc = self._get_doc(name)
  File "/usr/lib/python2.6/site-packages/oct2py/core.py", line 553, in _get_doc
    verbose=False)
  File "/usr/lib/python2.6/site-packages/oct2py/core.py", line 284, in eval
    post_call=post_call)
  File "/usr/lib/python2.6/site-packages/oct2py/core.py", line 729, in evaluate
    self._handle_first_run()
  File "/usr/lib/python2.6/site-packages/oct2py/core.py", line 827, in _handle_first_run
    subprocess.check_output('which gnuplot', shell=True)
AttributeError: 'module' object has no attribute 'check_output'

Any suggestions on how I can evaluate these feedback messages and how I can mitigate them?

Many Thanks,

**Comment by blink1073** [comment]
Ah, sorry, I missed the fact that you were using python2.6.  I no longer support Python 2.6, because it lacks too many features I've come to rely on, including `subprocess.check_output`.  Do you have the ability to install the Software Collections Library on your system?

http://wiki.centos.org/AdditionalResources/Repositories/SCL

**Comment by KainoaCulverhouse** [comment]
Hi @blink1073, thank you for the response I appreciate it.

**Comment by KainoaCulverhouse** [comment]
Hi @blink1073, thank you for the response I appreciate it.

**Comment by KainoaCulverhouse** [comment]
I installed the library.

 I have previously installed the 'pip' package to install the oct2py package. However, the packages seam to only be associated with python2.6, would you have any recommendations how I can go about having oct2py 'point to' or communicate with python3.3 rather than python2.6?

**Comment by KainoaCulverhouse** [comment]
Nevermind. I figured it out and have python2.7 calling functions from octave using the first step you suggested.

Appreciate the help.

**Comment by blink1073** [comment]
No problem!
