### ISSUE TITLE
Returning a data structure using oct2py in Python 2.7

### ISSUE THREAD

**Issue by KainoaCulverhouse** [blink1073/oct2py#75]
Hello,

I am attempting to return a data structure using a custom function in Octave-4.0.0 and calling it in python.

In octave I wrote a simple function to return a structure:

function y = f(a,b)
y.a = a;
y.b = b;
endfunction

when I use the function in the octave command window the following happens as expected:

y = f(1,2)
y =

  scalar structure containing the fields:

    a =  1
    b =  2

Next, I try to use the function in python. I have already imported octave in the current python session using ('from oct2py import Oct2Py; octave = Oct2Py(executable='/usr/bin/octave-cli-4.0.0')
When I try to attempt '>>> octave.f(1,2)' or '>>> y = octave.f(1,2)' the following error occurs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/oct2py/core.py", line 409, in octave_command
    return self._call(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/oct2py/core.py", line 516, in _call
    data = self.eval(cmd, temp_dir=temp_dir, **eval_kwargs)
  File "/usr/local/lib/python2.7/site-packages/oct2py/core.py", line 297, in eval
    data = self._reader.extract_file()
  File "/usr/local/lib/python2.7/site-packages/oct2py/matread.py", line 88, in extract_file
    data[key] = get_data(data[key])
  File "/usr/local/lib/python2.7/site-packages/oct2py/matread.py", line 139, in get_data
    for i in range(val.size)])
  File "/usr/local/lib/python2.7/site-packages/oct2py/matread.py", line 99, in get_data
    if "'|O" in str(val.dtype) or "O'" in str(val.dtype):
AttributeError: 'mat_struct' object has no attribute 'dtype'

Are data structures able to be returned in python using oct2py? If so how can I go about fixing this?

Thanks.

**Comment by blink1073** [comment]
I think this bug is solvable, I'll take a look tonight.

**Comment by blink1073** [comment]
(note: this is a bug in Oct2Py, I don't think there's anything you can do differently), and thanks for the report @KainoaCulverhouse!

**Comment by KainoaCulverhouse** [comment]
Thank You @blink1073 ,

My suggestion may or may not help but im understanding that y is returned as a data type struct rather than a float. Im trying to see if its possible to convert a struct to a float in octave (no idea if thats possible) because maybe 'dtype' is looking for a float64 rather than a struct.

**Comment by blink1073** [comment]
@KainoaCulverhouse, Oct2Py does support Octave structs.  In this case I think it has more to do with the shape of the data.  I'll test against your specific data and add it to the test suite, once I figure out the bug.

**Comment by KainoaCulverhouse** [comment]
okay @blink1073 i appreciate it

**Comment by blink1073** [comment]
Strange, it works for me (I called it testfunc):

```python
In [2]: octave.testfunc(1, 2)
Out[2]: {'a': 1.0, 'b': 2.0}
```

What version of Oct2Py are you using:  `oct2py.__version__`?

**Comment by KainoaCulverhouse** [comment]
I am using version 3.2.0

**Comment by KainoaCulverhouse** [comment]
strange, I also get the same error if I simply call '>>> octave.struct()'.

**Comment by blink1073** [comment]
Ah, I get the error now when calling `octave.struct()`, that should help me fix the bug...

**Comment by blink1073** [comment]
Okay, both should be fixed.  You can try using the latest development version, or wait until the next release (should be this weekend).

**Comment by blink1073** [comment]
And now released!

**Comment by blink1073** [comment]
Closing as fixed.
