### ISSUE TITLE
Windows 145 error: Directory is not empty in core.py shutil.rmtree

### ISSUE THREAD

**Issue by gunjannaik** [blink1073/oct2py#76]
I am using oct2py with Anaconda distribution. Sometime I am getting an error as 'WindowsError: [Error 145] The directory is not empty "path of temporary directory" '. I checked the temporary folder and it is empty. How to solve this issue?

**Comment by blink1073** [comment]
Thanks for the report @gunjannaik, I just released a new version to address this, can you try `pip install -U oct2py`?

**Comment by blink1073** [comment]
Closing due to lack of response, feel free to reopen if this is still an issue @gunjannaik.

**Comment by gunjannaik** [comment]
Thanks @blink1073 ...Sorry I forget to close it.

**Comment by inoppiy** [comment]
Hi, Is cause of this problem python's bug?

**Comment by blink1073** [comment]
I'm not sure, I can't remember the context of the fix anymore.
