### ISSUE TITLE
Oct2py version for Ocate ver 4.0.0 

### ISSUE THREAD

**Issue by uozden** [blink1073/oct2py#78]
Dear Blink1075
Which version of oct2py does work with Octave 4.0.0 on Windows ?
Thanks in advance

**Comment by blink1073** [comment]
Hi @uozden, the latest version (3.3.3) should work with Octave 4.0.  You can install it as `pip install -U oct2py`

**Comment by uozden** [comment]
Dear Blink1075,
Thank you very much for your promt response. I right away will install  ver.3.3.3. 
Regards

**Comment by uozden** [comment]
Dear blink1073
As you suggested I installed oct2py ver 3.3.3 on Windows 10, with Python ver 3.4. Test your 2 commands and gave the following errors. " ..CalledProcessError: Command '['octave', '--version']' returned non-zero exit status 3221225785.."Thank you for your help. 

import oct2py
Traceback (most recent call last):

  File "<ipython-input-1-3615f4c3421b>", line 1, in <module>
    import oct2py

  File "C:\...\python-3.4.3\lib\site-packages\oct2py\__init__.py", line 69, in <module>
    octave = Oct2Py()

  File "C:\...\python-3.4.3\lib\site-packages\oct2py\core.py", line 86, in __init__
    self.restart()

  File "C:\....\python-3.4.3\lib\site-packages\oct2py\core.py", line 391, in restart
    self._session = _Session(self._executable, self.logger)

  File "C:\...\python-3.4.3\lib\site-packages\oct2py\core.py", line 643, in __init__
    self.proc = self.start(executable)

  File "C:\.....\python-3.4.3\lib\site-packages\oct2py\core.py", line 700, in start
    info = subprocess.check_output([executable, '--version'])

  File "C:\....\python-3.4.3\lib\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)

CalledProcessError: Command '['octave', '--version']' returned non-zero exit status 3221225785


import numpy as np

from oct2py import Oct2Py
Traceback (most recent call last):

  File "<ipython-input-3-061e55321f23>", line 1, in <module>
    from oct2py import Oct2Py

  File "C:\....\python-3.4.3\lib\site-packages\oct2py\__init__.py", line 69, in <module>
    octave = Oct2Py()

  File "C:\....\python-3.4.3\lib\site-packages\oct2py\core.py", line 86, in __init__
    self.restart()

  File "C:\...\python-3.4.3\lib\site-packages\oct2py\core.py", line 391, in restart
    self._session = _Session(self._executable, self.logger)

  File "C:\...\lib\site-packages\oct2py\core.py", line 643, in __init__
    self.proc = self.start(executable)

  File "C:\....\python-3.4.3\lib\site-packages\oct2py\core.py", line 700, in start
    info = subprocess.check_output([executable, '--version'])

  File "C:\....\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)

CalledProcessError: Command '['octave', '--version']' returned non-zero exit status 3221225785

**Comment by blink1073** [comment]
@uozden, it looks like `octave` is not recognized as a command in your environment.  You can follow the instructions [here](http://blink1073.github.io/oct2py/source/installation.html#gnu-octave-installation) for how to set it up.

**Comment by uozden** [comment]
Dear Steven,
Thanks for reverting us. We have set it up s as suggested in the link. Also to tested by typing octave in a command window . Octave started with GUI (ver .4.0.0).However I  am still getting the same error of " CalledProcessError: Command '['octave', '--version']' returned non-zero exit status 3221225785". What would you suggest to do ?. Regards.

**Comment by blink1073** [comment]
And running `python -c "import oct2py"` from that same command line shows the error?

You could also try: `python -c "import subprocess; subprocess.check_output(['octave', '--version'])"`

**Comment by uozden** [comment]
Dear Steven,
Tried both command at the command line and gave the same error as follows. Thanks for your helop as oct2py is important package for me if I can run it.  
" “Check output raise: CalledProcessError(retcode, process.args, outpot=outpu) 
Subprocess.CalledProcessError: Command ‘[ ‘octave’, ‘—version’] return non-zero exit status 3221225785”
I am using “ WinPython -32bit 3.4.3.6 “  and Octave 4.0.0.0 at Path “C:\Octave\Octave-4.0.0\bin” on Windows10.

**Comment by blink1073** [comment]
You should add just the path to the directory “C:.......\Octave-4.0.0\bin”, which should pick up `bin\octave.exe`.

**Comment by blink1073** [comment]
Another option is to use the `OCTAVE` environment variable, which `oct2py` recognizes, and try setting it to the full path of each of those executable files and see if one works.

**Comment by blink1073** [comment]
Closing due to lack of feedback, fail free to reopen.
