### ISSUE TITLE
ipython hangs after loading octavemagic

### ISSUE THREAD

**Issue by RiyanshKarani01235** [blink1073/oct2py#79]
Hello, here is the problem I have been facing for a while now and it would be very kind of you if you could solve this, since i need to run octave commands from Ipython notebook.
when I type the following command in Ipython notebook : 
%load_ext oct2py.ipython
3 to 4 octave cli windows open up

after this, when I type any octave command (eg : %octave x = [1 2];), ipython notebook hangs. 

i am using using:
octave-3.8.0
ipython notebook 4.0.4
oct2py installed using pip3 install oct2py

**Comment by blink1073** [comment]
Hi @ironstein1994, can you tell me your operating system and the output of `import oct2py; oct2py.__version__`.?

**Comment by ironstein1994** [comment]
@blink1073 thanks for replying.
My operating system is Mac osx 10.11.1 

>>import oct2py
>>oct2py.__version__
'3.3.3'

**Comment by blink1073** [comment]
Hmm, I have a nearly identical setup:

octave-3.8.0
oct2py 3.3.3
notebook 4.06
python 3.4.3
OSX 10.10.5

I tried your code above and it works just fine.  Is it printing anything in the terminal that you launch the notebook from?

**Comment by ironstein1994** [comment]
@blink1073 when I run the command, a lot of octave terminals open up.vis that normal ?

**Comment by blink1073** [comment]
No, I wonder if it is El Capitan causing trouble. 



—

**Comment by blink1073** [comment]
@ironstein1994, do you mind trying with the latest release (3.4)?

**Comment by blink1073** [comment]
Closing due to lack of reply, please feel free to reopen.
