### ISSUE TITLE
oct2py problems with Octave4.0

### ISSUE THREAD

**Issue by ernest2015** [blink1073/oct2py#82]
Hello,
I have a problem with oct2py and Octave4.0 connection. Theese basic ommands complain that octave couldn't be found:

from oct2py import Oct2Py
oc = Oct2Py()

It tries to run a graphical version of python and then hang up.

I think the main problem causes Octave 4.0.0 because a command octave inside bin folder by default (without parameters) run a GUI version of Octave, but oct2py always run the command that causes an error instead of octave.exe I would like to run octave-cli-4.0.0.exe command but I don't know how. 

I have solved the problem but I'm not very satisfied with the solution. I have renamed octave.exe into a octaveOriginal.exe and octave-cli.exe into a octave.exe. To recap: I would like to run CLI vesrion of Octave  octave-cli.exe which is now renamed into an octave.exe. Now oct2py can successfully get CLI version of Octave and it seems that everything works as expected (I have successfully tested all examples from your example page: http://blink1073.github.io/oct2py/source/demo.html).

I'm honestly grateful for any more natural way without modifying names of Octave files.

Best regards
Ernest

**Comment by blink1073** [comment]
Hi @ernest2015, you can set the `OCTAVE_EXECUTABLE` environment variable to be the path to `octave-cli-4.0.0.exe`.

**Comment by blink1073** [comment]
Hi @ernest2015, do you mind trying with the latest release (3.4)?

**Comment by dalito** [comment]
I am not ernest2015, but I can confirm that oct2py 3.4.0 works with Octave 4.0 on Windows 7 when setting the environment variable OCTAVE_EXECUTABLE as you wrote.

**Comment by blink1073** [comment]
Thanks @dalito, I'll close this one.  @ernest2015, feel free to reopen if need be.
