### ISSUE TITLE
Renaming(?) speed_check -- speed_test

### ISSUE THREAD

**Issue by dalito** [blink1073/oct2py#84]
I recognised that the documentation as well as parts of the code in version 3.4.0 and current master refer to speed_test which was obviously renamed to speed_check.

See e.g.
http://blink1073.github.io/oct2py/source/info.html?highlight=speed#speed
https://github.com/blink1073/oct2py/blob/master/oct2py/__init__.py#L26

BTW, thank you very much for making oct2py available. I discovered it this week and it has been extremely useful in testing out some matlab code published along with scientific papers.

**Comment by blink1073** [comment]
Thanks, I'm glad you have found it useful!  Fixed and released `3.4.1`.
