### ISSUE TITLE
Example in which  addpath hangs

### ISSUE THREAD

**Issue by ligon** [blink1073/oct2py#87]
Addpath  consistently hangs when used in an imported module.

Consider the following three files, all kept in /tmp.  The file baz.m is an  octave file.  The python file foo.py imports oct2py and calls baz.m, and works correctly.  The python file bar imports foo, and hangs at addpath.

A further strangeness: if one runs bar.py in  ipython it hangs.   But ^C^C gets one back to the  prompt, *and then bar.py will run as expected*. 

#+name: baz
#+BEGIN_SRC octave :tangle /tmp/baz.m

    function [s]=baz(x);
      s=x
    endfunction;

#+END_SRC

#+name: foo
#+BEGIN_SRC python :results  output :tangle /tmp/foo.py

    import oct2py
    from oct2py import octave
    octave.addpath('/tmp/')

    def foo():
        return octave.baz("Hello world?")

    if __name__=='__main__': print foo()
#+END_SRC

#+results: foo
: Hello world?

#+name: bar
#+BEGIN_SRC python :dir /tmp/ :results output :tangle /tmp/bar.py

    import foo
    print foo.foo()

#+END_SRC

#+results: bar

    <<HANGS>>

**Comment by blink1073** [comment]
Hi @ligon, I'm not sure what the problem could be off the top of my head.  I am traveling this weekend but will have a look when I get back.

**Comment by blink1073** [comment]
I took a look at this, and the problem seems to come from executing code on input.  I tried finding a proper fix but it eludes me.  You can put your `addpath()` function in the `foo()` call as a workaround for now.

**Comment by ligon** [comment]
Thanks for looking at this.  The workaround is what I'm using now, but  I'd
like to distribute the  code which calls octave as a module, which I guess
will lead to users of the module being bitten by this.

Browsing the issues you have on github, it looks like about 20% of them are
related to addpath, and this seems like a problem which may affect many
users.

Happy to help in any further trouble-shooting, and really appreciate the
work you've put in on this excellent project.

-Ethan Ligon

**Comment by blink1073** [comment]
Reading from a `pty` in a thread was causing the issue, fix released in `v3.5.6`.

**Comment by ligon** [comment]
Excellent; thanks for taking the trouble to fix this.

I can confirm that this solves the problem I identified.

-Ethan

**Comment by blink1073** [comment]
Great!
