### ISSUE TITLE
Bug when cell arrays contain complex values

### ISSUE THREAD

**Issue by fstj** [blink1073/oct2py#88]
Hi,

Cell arrays containing complex values seem to be mishandled by oct2py.

For example if I define the Octave function bug_cell with this code:
``` Octave
function [res] = bug_cell()
    res = {1.2+2.4i, 3};
```
and I run it from Python via oct2py with:
``` Python
import oct2py
oc = oct2py.Oct2Py()
res = oc.bug_cell()
print(res)
```
I get `None` as a result. If I put only real values in `res` I get a satisfying result.

My OS is Ubuntu 15.10 and I'm using oct2py 3.5.6 in Python 3.4.3 and Octave 4.0.0.

Any idea how to solve this?

**Comment by blink1073** [comment]
Hi @fstj, thanks for the detailed report, this is fixed in `3.5.7`:

```python
In [1]: %paste
import oct2py
oc = oct2py.Oct2Py()
res = oc.bug_cell()
print(res)

## -- End pasted text --
[array([ 1.2+2.4j]), array([ 3.])]
```

**Comment by fstj** [comment]
I confirm that it works now.
Thanks for the quick fix, and for your work on oct2py in general.

**Comment by blink1073** [comment]
My pleasure, thank you for the kind words.
