### ISSUE TITLE
oct2py crashing python.exe in Jupyter

### ISSUE THREAD

**Issue by danzimmerman** [blink1073/oct2py#89]
I'm having an issue with oct2py with Jupyter on Win 7 Ultimate 64 bit SP1 

Octave is 4.0.0, oct2py is 3.5.6, Jupyter is 4.1.0 and is running on:
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]

After a little bit of debugging, it seems like oct2py is installed properly and partially working. I can import, push in an array, plot it, use the keyboard() interactive version. But it looks like anything that would print in the Jupyter notebook like `octave.pull('y')` or even something like `octave.eval('pwd()')` crashes the kernel.

![image](https://cloud.githubusercontent.com/assets/4365714/15484320/7ba265bc-2107-11e6-8e01-7bef114adbce.png)

Plots output from the Jupyter screenshot above:

![image](https://cloud.githubusercontent.com/assets/4365714/15484341/91684736-2107-11e6-8a95-47ff93b513ac.png)

**Comment by blink1073** [comment]
I just tried with Octave 4.0.1, oct2py v3.5.7, Jupyter 4.1.0, Python 2.7 64-bit on Anaconda and Windows 7 and your examples worked fine for me.  Can you try running the code below from a regular `ipython` prompt and see if there is any traceback?

```python
from oct2py import octave
octave.eval('pwd')
```

**Comment by danzimmerman** [comment]
Unfortunately no traceback. Same error dialog "python.exe has stopped working -> Close program" and then a silent exit of IPython after I click it away.

![image](https://cloud.githubusercontent.com/assets/4365714/15509865/15393aca-21a3-11e6-834f-422766ebde40.png)

**Comment by blink1073** [comment]
Okay, I can reproduce after upgrading Anaconda.  Not sure what is causing it yet.

**Comment by blink1073** [comment]
I traced the issue to `scipy.io.loadmat` not segfaulting under these conditions, see https://github.com/ContinuumIO/anaconda-issues/issues/650.

**Comment by blink1073** [comment]
Downgrading to `conda install scipy=0.16.0` resolved the issue.

**Comment by danzimmerman** [comment]
Yes, that resolved it here as well, thanks.

**Comment by blink1073** [comment]
Closing as fixed.
