### ISSUE TITLE
Interactive prompt initiated when loading symbolic package

### ISSUE THREAD

**Issue by suever** [blink1073/oct2py#91]
The [symbolic octave package](http://octave.sourceforge.net/symbolic/) spawns an external python process and displays a greeting message followed by a python prompt `>>>`. This triggers the interactive mode of `oct2py` because the [check for an interactive prompt](https://github.com/blink1073/oct2py/blob/master/oct2py/core.py#L864
) in `oct2py` is `line.endswith('> ')` which incorrectly detects the Python prompt (`>>>`) to be an Octave prompt.

This can be fixed by altering this check to ensure that it is *not* a Python prompt:

```
if line.endswith('> ') and not line.endswith('>>> '):
    self.interact(line)
```

To install the symbolic package:

In python:

```
pip install sympy
```

In Octave:
```
pkg install -forge symbolic
pkg load symbolic
```

**Comment by blink1073** [comment]
Closed by #92.
