### ISSUE TITLE
Getting logical types into Oct2Py

### ISSUE THREAD

**Issue by brianthelion** [blink1073/oct2py#94]
The following fails on 3.5.9:

``` python
import oct2py
import numpy as np
engine = oct2py.Oct2Py(convert_to_float=False)
assert engine.islogical(np.array([0, 1], dtype='bool'))
```

What's the correct method for passing logicals into Oct2Py?
Thanks!

**Comment by blink1073** [comment]
Hi @brianthelion, thank you for the report.  Handling of booleans was not available in older versions of `scipy.savemat`: https://github.com/scipy/scipy/pull/4286.  This will be fixed by #95.

**Comment by blink1073** [comment]
I don't see a good way to make this work.  The scipy fix is only available in version 0.16 (oct2py supports 0.13), and even with the fix I am getting segfaults.  I'm going to call this won't fix from my standpoint.

**Comment by dansteingart** [comment]
@blink1073 does this mean that booleans cannot be passed at all to any function in octave from python?  thanks in advance?

**Comment by blink1073** [comment]
In `oct2py` 3.x they are passed as integer types.  In `oct2py` 4.x they will be passed as logical types.  See #108.
