### ISSUE TITLE
Crash at initialization due to output pagination

### ISSUE THREAD

**Issue by andrescodas** [blink1073/oct2py#97]
During initialization of octave ~/.octaverc is called. If this execution prints a lot and "more off" is not called before  oct2py crashes.

A workaround is to make sure that 'more off' is called on the first line of  ~/.octaverc

**Comment by blink1073** [comment]
Thanks for the report.  I believe the solution from this end is to use `--no-init-file`, set `more off`, and then evaluate the initialization files manually.
